### ISSUE TITLE
Add paper to Awesome Deep Neuroevolution

### ISSUE THREAD

**Issue by Alro10** [HaolingZHANG/ReverseEncodingTree#5]
Hello,

I added your paper and the implementation to my repo:

https://github.com/Alro10/awesome-deep-neuroevolution

Congrats for this amazing work!

Regards,

**Comment by huckiyang** [comment]
Hi @Alro10 thank you for the warm notification. We are glad to be part of the deep NE collection. Cheers,

**Comment by HaolingZHANG** [comment]
Hi @Alro10, 

Thank you for the warm notification.
If you have any questions about algorithm theory or codes, please do not hesitate to contact me.

Cheers,

Zhang

**Comment by huckiyang** [comment]
@Alro10 Hello, Alexander, our paper has been accepted to IEEE CEC 2020.
An updated version could be found out [here](https://arxiv.org/abs/2002.00539).
Feel free to update it in your nice collection. Cheers,
